### ISSUE TITLE
Can Not Print Malformed PDF

### ISSUE THREAD

**Issue by ericcumbee** [sarahgoldman/cordova-print-pdf-plugin#9]
I am trying to take a pdf created using jsPDF and print it. So far I've tested it on a Nexus 6 with Android 6, and an ASUS K10 tablet running 4.4.

```
var print = function(){
      window.plugins.PrintPDF.isPrintingAvailable(function(dataPDF){
        window.plugins.PrintPDF.print({
          data: dataPDF,
          type: 'data',
          title: 'Voter Registration Application',
          dialogX: -1,
          DialogY: -1,
          success:function(result){
            console.log(result);
          },
          error:function(result){
            console.log(result);
          }
        });
      });
    };
    setTimeout(print(pdf),2000);

```

Both cases I am running into the following error. I thought it was something wrong with my pdf that was being generated so I Base64 encoded a pdf i downloaded from the internet and am getting the same result. 

On Device I am getting an error that the Print Spooler Service has stopped. 

```
01-20 15:33:05.215: E/PdfManipulationService(16834):    at com.android.printspooler.renderer.PdfManipulationService$PdfRendererImpl.openDocument(PdfManipulationService.java:90)
01-20 15:33:05.215: E/PdfManipulationService(16834):    at com.android.printspooler.renderer.IPdfRenderer$Stub.onTransact(IPdfRenderer.java:58)
01-20 15:33:05.240: E/AndroidRuntime(16312): java.lang.RuntimeException: Cannot print a malformed PDF file
01-20 15:33:05.240: E/AndroidRuntime(16312):    at android.print.PrintManager$PrintDocumentAdapterDelegate$MyHandler.handleMessage(PrintManager.java:815)
```

**Comment by sarahgoldman** [comment]
I've noticed in your code that you are using the variable passed through the isPrintingAvailable callback function as the pdf data, however the variable passed to the callback is a boolean depending on if printing is available or not. You probably want something more like:

```
   var print = function(dataPDF){

      window.plugins.PrintPDF.isPrintingAvailable(function(isAvailable){
        if (isAvailable) {
        window.plugins.PrintPDF.print({
          data: dataPDF,
          type: 'data',
          title: 'Voter Registration Application',
          dialogX: -1,
          DialogY: -1,
          success:function(result){
            console.log(result);
          },
          error:function(result){
            console.log(result);
          }
        });
        } else {
           alert('printing not available');
        }
      });
    };
    setTimeout(print(pdf),2000);
```

**Comment by ericcumbee** [comment]
Thank you so much, I'll give that a shot when I get back to this project.

**Comment by sarahgoldman** [comment]
Also, make sure you omit "data:application/pdf;base64," part from base64 string. You might have to do a string replace on the jsPDF result if that part is contained.
